name: Manual
on:
  workflow_dispatch:                        # 手動実行のイベント
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      log-level:
        type: choice
        options:
          - info
          - warn
          - error

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Log greeting with level
        run: |
          echo "${{ inputs.greeting }} : Logging level is ${{ inputs.log-level }}"

